name: Flutter Web App Build Phase

on:
  workflow_call:

jobs:
  build:
    defaults:
      run:
        working-directory: ./app
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: install app dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Run tests
        working-directory: ./app
        run: flutter test

      - name: Build flutter web
        working-directory: ./app
        run: flutter build web

      - name: 'Upload Web Build Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: web-assets
          path: ./build/web/