name: Main Pipeline

on:
  push:
  pull_request:
    types:
      - opened

jobs:
  CI:
    name: Flutter Continuous Integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install App Dependencies
        run: flutter pub get

      - name: Set up lcov
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install lcov -y

      - name: Run Tests
        run: flutter test --coverage
      - name: Report code coverage
        uses: fjlopezs/lcov-reporter-action@v1.0.0
        with:
          lcov-file: ./app/coverage/lcov.info
