name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  CICD_Pipeline:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./app

    steps:
      - uses: actions/checkout@v4

      #- name: install app dependencies
      #  working-directory: ./app
      #  run: flutter pub get
#
      #- name: Run tests
      #  working-directory: ./app
      #  run: flutter test
#
      #- name: Build flutter web
      #  working-directory: ./app
      #  run: flutter build web

      - name: Find Working Directory
        run: |
          pwd
          ls -a
      - name: Build Web
        uses: ./.github/workflows/build_phase.yml
        with:
          app_dir: ./app
      #- name: Deploy
      #  uses: ./.github/workflows/deploy-phase.yml
