name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Setup_Runner:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4

      #- name: install app dependencies
      #  working-directory: ./app
      #  run: flutter pub get
#
      #- name: Run tests
      #  working-directory: ./app
      #  run: flutter test
#
      #- name: Build flutter web
      #  working-directory: ./app
      #  run: flutter build web
  Build_Phase:
    uses: ./.github/workflows/build_phase.yml
      with:
        app_dir: ./app
      #- name: Deploy
      #  uses: ./.github/workflows/deploy-phase.yml
