name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Build_Phase:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/build_phase.yml
      with:
        app_dir: ./app
