name: Main Pipeline

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  CI:
    name: Flutter Continuous Integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install App Dependencies
        run: flutter pub get

      - name: Set up lcov
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install lcov -y

      - name: Run Tests
        run: flutter test --coverage
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 50
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./app
          update-comment: true
          
      - name: Build Flutter Web
        run: flutter build web
      - name: Web Deploy - GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web/
      #- uses: FirebaseExtended/action-hosting-deploy@v0
      #  with:
      #    repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
      #    expires: 30d
      #    projectId: flutterdilemma
