name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: install dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Run tests
        working-directory: ./app
        run: flutter test

      - name: Build flutter web
        working-directory: ./app
        run: flutter build web

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b gh-pages
          mv app/build/web/* .
          git add .
          git commit -m "Deploy Flutter Web"
          git push origin gh-pages
