name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Pipeline:
    name: Flutter CI/CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_phase.yml
        with:
          app_dir: ./app
