name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Setup_Runner:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4

  Build_Phase:
    needs: Setup_Runner
    uses: ./.github/workflows/build_phase.yml
    with:
      app_dir: ./app
